--liquibase formatted sql
--changeSet dev_0001:001-01

CREATE TABLE users
(
    user_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(20)  NOT NULL,
    email     VARCHAR(256) NOT NULL
);

-- rollback DROP TABLE users;