--liquibase formatted sql
--changeSet dev_0001:002-01

CREATE TABLE roles
(
    role_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role VARCHAR(20) NOT NULL UNIQUE
);

-- rollback DROP TABLE roles;