--liquibase formatted sql
--changeSet dev_0001:001-01

CREATE TABLE users
(
    user_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id   INT          NOT NULL  REFERENCES roles (role_id),
    full_name VARCHAR(20)  NOT NULL,
    password  VARCHAR(256) NOT NULL,
    date_of_creation TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- rollback DROP TABLE users;